### ISSUE TITLE
Can `Timestamp` in metadata be overwritten? 

### ISSUE THREAD

**Issue by zhuliice** [awslabs/aws-embedded-metrics-dotnet#45]
By calling this SDK to send EMF logs, it seems we cannot define the timestamp of the metrics. 
The timestamp is generated at https://github.com/awslabs/aws-embedded-metrics-dotnet/blob/fec85c5859450d8061e5e515f6ca229d656eb7c9/src/Amazon.CloudWatch.EMF/Model/MetaData.cs#L27-L29, and I don't find the way to overwrite it. 

However, we could assign `Timestamp` as wanted, if we construct the EMF log by our own, see: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Generation_PutLogEvents.html.

**Comment by zhuliice** [comment]
@markkuhn We would like to have this feature. Could someone fix it soon? If not, I will try to propose a PR, but it may take some time for me. Thanks!

**Comment by rayabagi** [comment]
Hi @zhuliice, Support to add custom timestamp is now supported. Pull request: (https://github.com/awslabs/aws-embedded-metrics-dotnet/pull/55). I am marking it as closed.
